# Generated by Django 4.0.3 on 2022-03-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_region_lan_sample_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='region_lan',
            name='language',
            field=models.CharField(default='', max_length=200),
        ),
    ]
